### ISSUE TITLE
Richiesta Programma Sisma ANAS in formato leggibile

### ISSUE THREAD

**Issue by aborruso** [ondata/ricostruzione_trasparente#11]
Visto quanto segnalato da @alesarrett nella issue #10 ho richiesto tramite [PEC] - il 21 febbraio 2017 -(http://www.stradeanas.it/it/contatti-pec) ad ANAS di pubblicare il loro 
[programma](https://github.com/ondata/ricostruzione_trasparente/files/787272/Programma.Sisma.Stralcio.1.Allegato.A.pdf) anche in formato nativo (probabilmente un foglio elettronico).

![image](https://cloud.githubusercontent.com/assets/30607/23122936/a5d44b3a-f766-11e6-8a94-de506a491be6.png)

**Comment by lorenzoperone** [comment]
Ho provato a convertire il pdf in file docx usando Microsoft Word 2016, questo permette di recuparere il testo a prezzo di una formattazione, all'apparenza, ancora peggiore della tabella.
[2_PDFsam_Programma Sisma Stralcio 1 Allegato A.docx](https://github.com/ondata/ricostruzione_trasparente/files/787455/2_PDFsam_Programma.Sisma.Stralcio.1.Allegato.A.docx)

**Comment by aborruso** [comment]
Arrivata la prima risposta via PEC:

> In merito alla Sua mail del 20/2/2017 – corrispondente alla pratica n. 505599 - Le comunichiamo che  la stessa è stata trasmessa all'Ufficio competente: Relazioni Esterne e Comunicazione della Direzione Generale ANAS S.p.A.della Direzione Generale ANAS S.p.A.
> 
> La ringraziamo per aver contattato il Servizio Clienti di ANAS S.p.A.

**Comment by aborruso** [comment]
Il dialogo continua e il [webteam di Anas SpA](stradeanas) ci ha inviato questo messaggio, che ci fatto piacere ricevere:

>Abbiamo letto con interesse l’articolo di Lorenzo Perone su https://t.co/DT1JPXf2qH relativo alla conversione del file PDF “Piano Anas per la viabilità della zona colpita dal terremoto” e abbiamo seguito la conversazione ondata/ricostruzione_trasparente su https://t.co/0X1mp9VqcV. 
>La trasparenza è un obiettivo comune e sulla ricostruzione post-sisma siamo impegnati in prima linea con i nostri tecnici e ingegneri. La pubblicazione del file PDF ha sicuramente creato problemi di leggibilità, ma lo sforzo verso la trasparenza è stato massimo fin da subito.
>Una pagina del sito web Anas è dedicata al nostro impegno nei piani di tutela del territorio (https://t.co/XXzS0IacYc) che ci vedono chiamati a lavorare anche su reti di competenza locale. Il comunicato stampa sul piano per il Centro Italia, con gli allegati (https://t.co/zLTynJg2tT), è stato rilanciato anche sui nostri canali social Facebook e Twitter. 
>Proprio nell’ottica della condivisione e trasparenza abbiamo pubblicato il file di “come leggere” l’allegato PDF, che - ci rendiamo conto - riporta tante informazioni, alcune di immediata comprensione solo per gli addetti ai lavori (per esempio, i codici criticità).
>Il nostro sforzo è continuo e siamo in attesa di poter pubblicare presto anche i file excel e una sintesi della relazione complessiva approvata dal Dipartimento di Protezione Civile.
>Far bene nella ricostruzione, controllare e agire con la massima trasparenza è obiettivo comune. Le persone Anas, vi assicuriamo, sono dedite al duro lavoro di sopralluogo, valutazione, verifica, progettazione, controllo e esecuzione delle opere, per far sì che la viabilità possa tornare alla normalità in terre e paesi dove la parola “normalità” purtroppo non ha più molto senso.
>Siamo sicuri che l’attivismo civico può fare la differenza aiutando il lavoro pubblico e appoggiamo l’idea che sta alla base della piattaforma “Ricostruzione Trasparente”.
>Vi informeremo appena i file saranno on line.
>Ciao, web team Anas

**Comment by aborruso** [comment]
Anas ha pubblicato il file in formato xls https://twitter.com/StradeAnas/status/835103888042823680
