### ISSUE TITLE
Cambio licenza da CC-BY-SA 3.0 a 4.0

### ISSUE THREAD

**Issue by alesarrett** [ondata/ricostruzione_trasparente#2]
Nel file https://github.com/ondata/ricostruzione_trasparente/blob/master/README.md la licenza assegnata è la CC-BY-SA 3.0
Consiglio il passaggio alla CC-BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/deed.it).

**Comment by lorenzoperone** [comment]
Inserito riferimento a CC-BY-SA 4.0
